site_name: Desarrollo de interfaces
site_url: https://jsanz994.github.io

docs_dir: src
site_dir: docs

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: es
  icon:
    logo: material/cellphone-arrow-down
  font:
    text: Nunito
    code: Roboto Mono
  palette:
    - scheme: default
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Resultados de aprendizaje:
    - 1. Introducción a FlutterFlow: 01-introduccion/index.md
    - 2. Accesibilidad y Usabilidad: 02-accesibilidad-y-usabilidad/index.md
